spring:
  datasource:
    url: jdbc:mysql://39.106.228.124:3306/param?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: param
    password: 1q1w1e1r
  jpa:
    show-sql: true
server:
  port: 8082

staffjoy:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"